---
# tasks file for polkadot-validator
- name: firewall setup
  import_tasks: firewall.yml

- name: journald config
  import_tasks: journald.yml

- name: user and group
  import_tasks: user.yml

- name: mount ext4
  import_tasks: mount_ext4.yml

- name: install gcp stack driver
  import_tasks: gcp_stack_driver.yml
  when: enable_gcp_stack_driver|default(false)|bool

- name: proxy setup
  import_tasks: proxy.yml

- name: service setup
  import_tasks: service.yml

- name: install binary
  import_role:
    name: polkadot-update-binary

- name: session management
  import_tasks: session.yml
