---
# tasks file for polkadot-validator
- name: firewall setup
  import_tasks: firewall.yml

- name: journald config
  import_tasks: journald.yml

- name: user and group
  import_tasks: user.yml

- name: proxy setup
  import_tasks: proxy.yml

- name: create a ext4 filesystem on /dev/sdb
  filesystem:
    fstype: ext4
    dev: /dev/sdb

- name: mount up device by id
  mount:
    path: "/home/{{ project }}"
    src: /dev/sdb
    fstype: ext4
    state: mounted

- name: change ownership data dir
  file:
    path: "/home/{{ project }}"
    state: directory
    recurse: yes
    owner: "{{ project }}"
    group: "{{ project }}"

- name: service setup
  import_tasks: service.yml

- name: install binary
  import_role:
    name: polkadot-update-binary

- name: session management
  import_tasks: session.yml

- name: install monitoring
  import_role:
    name: monitoring
