---
- name: create an ext4 filesystem
  filesystem:
    fstype: ext4
    dev: "{{ ext4Dev }}"
  when:
    - ext4Dev != ""

- name: mount up device by id
  mount:
    path: "{{ ext4Path }}"
    src: "{{ ext4Dev }}"
    fstype: ext4
    state: mounted
  when:
    - ext4Path != ""

- name: change ownership
  file:
    path: "{{ ext4Path }}"
    state: directory
    recurse: yes
    owner: "{{ project }}"
    group: "{{ project }}"
  when:
    - ext4Path != ""
