---
- name: "create {{ ssh_user }} group"
  group:
    name: "{{ ssh_user }}"
    state: present

- name: "add {{ ssh_user }} user"
  user:
    name: "{{ ssh_user }}"
    group: "{{ ssh_user }}"
    append: yes

- name: Sync ssh authorized keys
  authorized_key:
    user: "{{ ssh_user }}"
    state: present
    key: "{{ lookup('file', item) }}"
  with_fileglob: "{{ ssh_key_path }}"
