- name: get command output
  shell: |
    set -o pipefail
    journalctl -u {{ project }} --no-pager > /root/{{ project }}.log
    tail -n 30 /root/{{ project }}.log
  become: yes
  args:
    executable: /bin/bash
  changed_when: False
  register: command_output

- name: result
  debug:
    var: command_output.stdout_lines

- name: remove log
  file:
    path: "/root/{{ project }}.log"
    state: absent
