- name: get command output
  shell: |
    set -o pipefail
    journalctl -u {{ project }} --no-pager > /root/{{ project }}.log
    tail -n 10000 /root/{{ project }}.log
  become: yes
  args:
    executable: /bin/bash
  changed_when: False
  register: command_output

- name: result
  debug:
    msg: "Command result: {{ command_output.stdout }}"

- name: remove log
  file:
    path: "/root/{{ project }}.log"
    state: absent
