- name: download db
  get_url:
    url: "https://storage.googleapis.com/{{ chain }}-db/db.tar.gz"
    dest: "/home/{{ project }}/.local/share/{{ project }}/chains/{{ polkadot_network_id }}//"
    mode: '0700'
    owner: "{{ project }}"
    group: "{{ project }}"

- name: stop polkadot service
  systemd:
    name: "{{ project }}.service"
    state: stopped

- name: unpack db
  shell: |
    set -o pipefail
    cd /home/{{ project }}/.local/share/{{ project }}/chains/{{ polkadot_network_id }}/
    mv db db.back
    tar xzf db.tar.gz
    rm db.tar.gz
    chown -R {{ project }}:{{ project }} db/
  args:
    executable: /bin/bash

- name: start polkadot service
  systemd:
    name: {{ project }}.service
    state: started
