- hosts: all
  become: yes
  strategy: free
  roles:
  - { role: node-exporter, when: "node_exporter_enabled|default(false)|bool == true" }
  - { role: vpnpeer-setup, when: "use_custom_vpn|default(false)|bool == false" }
  - polkadot-common

- hosts: all
  become: yes
  roles:
  - { role: vpnpeer, when: "use_custom_vpn|default(false)|bool == false" }
  - common

- hosts: public
  become: yes
  roles:
  - polkadot-public

- hosts: validator
  become: yes
  roles:
  - polkadot-validator
  - polkadot-validator-session-info
